In [22]:
import pandas as pd
from data_exploration2 import Sales_Reviews

In [23]:
r=Sales_Reviews("Education",3)

In [27]:
import simplejson
pd.DataFrame(simplejson.loads(r))

,Sentiment_polarity,asin,billdate,index,nodeid,numunits,productid
0,0.195136,0005126207,1298937600000,0,7009083011,1,11083
1,0.195136,0005126207,1299024000000,1,7009083011,1,11083
2,0.195136,0005126207,1299110400000,2,7009083011,1,11083
3,0.195136,0005126207,1299196800000,3,7009083011,1,11083
4,0.195136,0005126207,1299456000000,4,7009083011,1,11083
5,0.195136,0005126207,1299628800000,5,7009083011,1,11083
6,0.195136,0005126207,1299801600000,6,7009083011,1,11083
7,0.195136,0005126207,1300147200000,7,7009083011,1,11083
8,0.195136,0005126207,1300233600000,8,7009083011,3,11083
9,0.195136,0005126207,1300752000000,9,7009083011,1,11083
10,0.195136,0005126207,1300838400000,10,7009083011,1,11083
11,0.195136,0005126207,1301356800000,11,7009083011,1,11083
12,0.195136,0005126207,1301443200000,12,7009083011,1,11083
13,0.318498,0005047218,1331164800000,13,3182,1,11067
14,0.318498,0005047218,1332374400000,14,3182,1,11067
15,0.318498,0005047218,1332460800000,15,3182,1,11067
16,0.318498,0005047218,1332892800000,16,3182,1,11067
17,0.318498,0005047218,1363219200000,17,3182,1,11067
18,0.180278,0005111994,1331337600000,18,3192,1,11082
19,0.180278,0005111994,1364515200000,19,3192,1,11082
20,0.180278,0005111994,1394150400000,20,3192,1,11082
21,0.180278,0005111994,1394496000000,21,3192,1,11082
22,0.180278,0005111994,1394582400000,22,3192,1,11082
23,0.180278,0005111994,1394755200000,23,3192,1,11082
24,0.180278,0005111994,1395360000000,24,3192,1,11082
25,0.180278,0005111994,1425427200000,25,3192,1,11082
26,0.258333,0002556324,1364256000000,26,355563011,1,10704
27,0.258333,0002556324,1395100800000,27,355563011,1,10704
28,0.169948,0006547184,1394496000000,28,8883935011,1,11864
29,0.330264,0007194420,1425254400000,29,3048961,1,12953
30,0.330264,0007194420,1425513600000,30,3048961,1,12953
31,0.330264,0007194420,1425945600000,31,3048961,1,12953
32,0.330264,0007194420,1426118400000,32,3048961,1,12953
33,0.330264,0007194420,1427068800000,33,3048961,1,12953
34,0.330264,0007194420,1427155200000,34,3048961,1,12953
35,-0.062996,0007197756,1425513600000,35,8975361011,1,12977
36,-0.062996,0007197756,1427673600000,36,8975361011,1,12977
37,0.256842,0007199058,1425600000000,37,10633,0,12991
38,0.256842,0007199058,1427328000000,38,10633,1,12991
39,0.139158,0007192428,1426723200000,39,9221735011,1,12925
40,0.131250,0007196369,1426723200000,40,11764643011,1,12966
41,-0.000678,0007196822,1426723200000,41,69829,1,12971
42,0.117271,000719739X,1426723200000,42,8975358011,0,12973
43,0.117271,000719739X,1427328000000,43,8975358011,0,12973
44,0.257292,0007201109,1426723200000,44,10680,1,13004
45,0.156667,0007194609,1427068800000,45,9205059011,1,12955
46,0.216948,0007197772,1427328000000,46,8975362011,1,12978
47,0.613393,0007198949,1427328000000,47,69842,0,12990
48,0.232566,0007201451,1427328000000,48,8975364011,1,13008
49,0.217321,0007201486,1427328000000,49,10687,1,13009
50,0.347481,0007201710,1427328000000,50,69849,1,13011
51,0.321431,0007194463,1458086400000,51,9205058011,1,12954